name: CI
on:
  - push
  - pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: coursier-cache-action
        uses: coursier/cache-action@v6.4.0
      - name: setup-scala
        uses: olafurpg/setup-scala@v10
      - run: sbt test